apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: coworkingspace-api-service
  name: coworkingspace-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      service: coworkingspace-api-service
  template:
    metadata:
      labels:
        service: coworkingspace-api-service
    spec:
      containers:
        - image: 456195656493.dkr.ecr.us-east-1.amazonaws.com/udacity-devops-project3:18
          name: coworkingspace-api-container
          imagePullPolicy: Always
          ports:
            - containerPort: 5153
          livenessProbe:
            httpGet:
              path: /health_check
              port: 5153
            initialDelaySeconds: 5
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              path: /readiness_check
              port: 5153
            initialDelaySeconds: 5
            timeoutSeconds: 5
          resources:
            requests:
              memory: "1000Mi"
              cpu: "250m"
            limits:
              memory: "2000Mi"
              cpu: "500m"
          envFrom:
            - secretRef:
                name: env-secret
            - configMapRef:
                name: env-config
      restartPolicy: Always