apiVersion: v1
kind: Service
metadata:
  labels:
    service: coworkingspace-api-service
  name: coworkingspace-api-service
spec:
  type: ClusterIP
  ports:
    - protocol: "TCP"
      port: 5153
      targetPort: 5153
  selector:
    service: coworkingspace-api-service