version: 0.2
env:
  variables:
    IMAGE_REPO_NAME: udacity-devops-project3
    CODE_BUILD_NUMBER: $(CODEBUILD_RESOLVED_SOURCE_VERSION)

phases:
  pre_build:
    commands:
      - echo "Logging to ECR"
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

  build:
    commands:
      - echo "Starting build on $(date)"
      - echo "Building Docker image..."
      - docker build -t $IMAGE_REPO_NAME:$CODE_BUILD_NUMBER ./analytics/.
      - docker tag $IMAGE_REPO_NAME:$CODE_BUILD_NUMBER $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$CODE_BUILD_NUMBER

  post_build:
    commands:
      - echo "Build completed on $(date)"
      - echo "Pushing Docker image to ECR..."
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$CODE_BUILD_NUMBER
